#!/bin/sh

# Test vtnspec

. ./testlib

cleanup(){
   rm -f $TMP.*
}

set -- `vtgen -r 192000 -sa=1.0,f=2000.00,p=10 -Tnow,+4.0 | 
   vtnspec  -f 2000.00 -r 0.25 |
     awk '{printf( "%.3f %.3e\n", atan2( $3, $2) * 180/3.14159, $4 )}'`

test "$1" = 10.000
result "t1a $1"
test "$2" = 7.071e-01
result "t1b $2"

set -- `vtgen -r 192000 -sa=1.0,f=2000.00,p=10 -Tnow,+3.7 | 
   vtnspec  -f 2000.00 -r 0.25 |
     awk '{printf( "%.3f %.3e\n", atan2( $3, $2) * 180/3.14159, $4 )}'`

test "$1" = 10.000
result "t2a $1"
test "$2" = 7.071e-01
result "t2b $2"

set -- `vtgen -r 192000 -sa=1.0,f=2000.00,p=10 -Tnow,+4.3 | 
   vtnspec  -f 2000.00 -r 0.25 |
     awk '{printf( "%.3f %.3e\n", atan2( $3, $2) * 180/3.14159, $4 )}'`

test "$1" = 10.000
result "t3a $1"
test "$2" = 7.071e-01
result "t3b $2"

set -- `vtgen -r 192000 -sa=1.0,f=2000.99,p=10 -Tnow,+8.1 | 
   vtnspec  -f 2000.99 -r 0.25 -c |
     awk '{printf( "%.3f %.3e\n", atan2( $3, $2) * 180/3.14159, $4 )}'`

test "$1" = 10.000
result "t4a $1"
test "$2" = 7.071e-01
result "t4b $2"

set -- `vtgen -r 192000 -sa=1.0,f=2000,p=10 | vtwspec -r 0.25 |
       awk '($1 == 2000){printf( "%.3f %.3e\n", atan2( $3, $2) * 180/3.14159, $4 )}'`

test "$1" = 10.000
result "t5a $1"
test "$2" = 7.071e-01
result "t5b $2"

set -- `vtgen -r 192000 -sa=1.0,f=2000 -Tnow,+30 | vtwspec -ar 0.5 |
       awk '($1 == 2000){printf( "%.3e\n", $2)}'`

test "$1" = 7.071e-01
result "t6 $1"

set -- `vtgen -r 192000 -sa=1.0,f=2000.99,p=10 -Tnow,+8.1 | 
   vtnspec  -f 2000.99 -r 0.25 -c |
     awk '{printf( "%.3f %.3e\n", atan2( $3, $2) * 180/3.14159, $4 )}'`

test "$1" = 10.000
result "t7a $1"
test "$2" = 7.071e-01
result "t7b $2"

cleanup

