/* Automatically generated by configure - do not modify */
#define ARCH_X86 1
#define CONFIG_DECODERS 1
#define HAVE_MALLOC_H 1
#undef  HAVE_MEMALIGN
#ifndef M_PI
 #define M_PI 3.14159265358979323846
#endif

