#!/bin/sh

opts=$*
pids=`fuser /tmp/vtprocs 2> /dev/null | sed 's/.*://'`

[ "$pids" = "" ] && exit

[ "$opts" = "" ] && {

   linux=`uname -a | grep -i linux` 
   [ "$linux" = "" ] &&
        opts="-o pid,pcpu,pmem,command" ||
        opts="-o pid,rtprio:2=RT,pcpu,pmem,command"
}

ps $opts -p $pids
